config/routes.rb
Rails.application.routes.draw do

  root to:"homes#top"
  get "home/about", to: "homes#about"
  devise_for :users
  resources :books, only: [:index, :show, :edit, :new, :create, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :destroy, :update]

  resources :users do
  resources :books, only: :index
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_one_attached :profile_image
    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save

     flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end


  def show
    @book2 = Book.find(params[:id])
    @books = Book.all
    @user = @book2.user
    @book = Book.new
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @book2 = Book.find(params[:id])
    @books = Book.all

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book2 = Book.find(params[:id])
    if @book2.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book2.id)
    else
      @books = Book.all
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id, :user_profile_image)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
    redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_userinfo.html.erb
<div class="col-md-3">
    <h2>User info</h2>

      <%= image_tag user.get_profile_image, size: "100x100" %>

      <table class="table">
       <tbody>
         <tr>
          <th>name</th>
          <th> <%= user.name %></th>
         </tr>
         <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
         </tr>
       </tbody>
        </table>
      <div class="row">
          <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
           <i class="fa-solid fa-user-gear"></i>
          <% end %>
      </div>

        <h2 class="mt-3">New book</h2>
         <%= form_with model: book do |f| %>
         <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, id:"book_title", class:"form-control" %>
          </div>
         <div class="form-group">
          <label for="book_body">Opinion</label>
           <%= f.text_area :body, id:"book_body", class:"form-control" %>
         </div>
         <div class="form_group">
          <%= f.submit "Create Book", class:"btn btn-success" %>
         </div>
       <% end %>

  </div>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
 <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h1>Editing Book</h1>
　　<% if @book2.errors.any? %>
     <h3><%= @book2.errors.count %>errors prohibited this obj from being saved:</h3>
     <ul>
      <% @book2.errors.full_messages.each do |message| %>
    　<li><%= message %></li>
    　 <% end %>
     </ul>
    <% end %>
     <%= form_with model: @book2 , url: book_path(@book2), method: :patch do |f| %>
         <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, id:"book_title", class:"form-control" %>
          </div>
         <div class="form-group">
          <label for="book_body">Opinion</label>
           <%= f.text_area :body, id:"book_body", class:"form-control" %>
         </div>
         <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
         </div>
       <% end %>
       <%= link_to "Show", book_path(@book2) %>
       <%= "|" %>
       <%= link_to "Back", books_path %>
   </div>
  </div>
 </div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div id="error_explanation">
   <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
     <ul>
     <% @book.errors.full_messages.each do |message| %>
    　<li><%= message %></li>
   　 <% end %>
  　　 </ul>
  　<% end %>
  　</div>
  <div class="row">
   <%= render 'userinfo', book: @book, user: @user %>
     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
       <table class="table table-hover table-inverse">
        <thead>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
        </thead>
        <tbody>
        <% @books.each do |book| %>
        <tr>
           <td><%= link_to user_path(book.user.id), class:"text-decoration-none" do %>
          　     <%= image_tag book.user.get_profile_image %>
          　    <% end %>
          　 </td>
            <td><%= link_to book_path(book.id) do %>
                <%= book.title %>
                <% end %>
            </td>
            <td><%= book.body %></td>
         </tr>
        <% end %>

         </tbody>
       </table>
      </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
 <div class="row">
   <%= render 'userinfo', book: @book, user: @user %>
    
  <div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
   <table class="table">
    <tbody>
      <tr>
         <td><%= link_to user_path(@book2.user) do %>
              <%= image_tag @book2.user.get_profile_image %><br>
              <%= @book2.user.name %>
             <% end %>
          </td>
          <td><%= link_to book_path(@book2) do %>
                <%= @book2.title %>
              <% end %>
          </td>
          <td><%= @book2.body %></td>
            <% if @book2.user == current_user %>
             <td><%= link_to "Edit", edit_book_path(@book2), class: "btn btn-success" %></td>
             <td><%= link_to " Destroy", book_path(@book2), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に消しますか？"  %></td>
            <% end %>
       </tr>
     </tbody>
   </table>
  </div>
 </div>
</div>