config/routes.rb
Rails.application.routes.draw do

  root to:"homes#top"
  get "home/about", to: "homes#about"
  devise_for :users
  resources :books, only: [:index, :show, :edit, :new, :create, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :destroy, :update]

  resources :users do
  resources :books, only: :index
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/a05b89f759.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
     <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
           <a class="navbar-brand" href="/" >
             <span>Bookers</span>
           </a>
        </a>
        
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
          
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>  
            <li>
               <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
               <i class="fa-solid fa-house" style="color:white;"></i>
               <%= "Home" %>
               <% end %>
            </li>
            <li>
              <%= link_to users_path, class: "nav-link text-light" do %>
               <i class="fa-solid fa-users"></i>
               <%= "Users" %>
               <% end %>
            </li>
            <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                <i class="fa-solid fa-book-open"></i>
                <%= "Books" %>
                <% end %>
          </li>
          
          <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
               <i class="fa-solid fa-right-from-bracket"></i>
               <%= "Log out" %>
               <% end %>
          </li>
        
        <% else %>
             <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fa-solid fa-house" style="color:white;"></i>
                <%= "Home" %>
                <% end %>
            </li>
            <li>
              <%= link_to home_about_path, class: "nav-link text-light" do %>
               <i class="fa-solid fa-link"></i>
               <%= "About" %>
               <% end %>
            </li>
         <li>
               <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
               <i class="fa-solid fa-user-plus"></i>
               <%= "Sign up" %>
               <% end %>
             </li>
             <li>
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                 <i class="fa-solid fa-right-to-bracket"></i>
                 <%= "Log in" %>
                 <% end %>
              </li>
           <% end %>
        </ul>
       </div>
      </div>
      
     </nav>
    </header>
    <main>
      
     <div><%= flash[:notice] %></div>
    <%= yield %>
    </main>
    <footer>
      <div class="conntainer mt-5">
        <div class="row">
         <div class="mx-auto">
            <p>Copy Right Inflatop.inc</p>
         </div>
        </div>
       </div>
    </footer>
   
  </body>
</html>